force-app/main/default/objects/Communication__c/Communication__c.object-meta.xml
<CustomObject>
    <description>Communication Object stores the details of communication between Agent and Lead with necessary information like mode of communication, content and some other important fields.</description>
    <label>Communication</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <description>For call Notes are stored in it.
For Chat- message body is stored.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Content</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Communication__c/fields/Medium_of_Communication__c.field-meta.xml
<CustomField>
    <fullName>Medium_of_Communication__c</fullName>
    <label>Medium of Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>call</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>chat</fullName>
            </value>
            <value>
                <fullName>whatsapp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication__c/fields/Sid__c.field-meta.xml
<CustomField>
    <fullName>Sid__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Communication__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Communication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConnectlyController.cls
public class ConnectlyController {
	@AuraEnabled
    public static String connect(String channel, String sourceId, String content, String Phone){
         
        Communication__c communication = new Communication__c();
        Communication.Medium_of_Communication__c= channel;
        communication.Source_Id__c=sourceId;
        communication.Content__c=content;
        communication.Sid__c=makecallout_for_sms(Phone, content);
        insert communication;
        system.debug('Id: '+communication.Id);
        system.debug('communication: '+communication);
        return communication.Id;
    }
    @AuraEnabled
    public static String makeCall(String sourceId, String Phone){
        Communication__c communication = new Communication__c();
        Communication.Medium_of_Communication__c= 'call';
        communication.Source_Id__c=sourceId;
        //communication.Content__c=content;
        communication.Sid__c=makecallout_for_caliing(Phone);
        insert communication;
        system.debug('Id: '+communication.Id);
        system.debug('communication: '+communication);
        return communication.Id;
    }
    @AuraEnabled(cacheable=true)
    public static List<Communication__c> get_details(String channel, String sourceId){
        system.debug('sourceId: '+sourceId);
        String sourceObject = Id.valueOf(sourceId).getSObjectType().getdescribe().Name;
        return [select Id,Name,Content__c,Status__c,CreatedDate,Medium_of_Communication__c,Is_Inbound__c 
                from Communication__c where Source_Id__c=:sourceId And Medium_of_Communication__c=:channel order by CreatedDate asc];
    }
    public static string makecallout_for_caliing(String Phone){
        String sid='';
        HttpRequest req = new HttpRequest();
        String endpoint = Label.TwilioUrl;
        req.setEndpoint(endpoint);
        req.setMethod('POST');
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        string username=Label.Twilio_Username;
        String password = Label.Twilio_Password;
		Blob headerValue = Blob.valueOf(username + ':' + password);
		String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
		req.setHeader('Authorization', authorizationHeader);
        
        String payload='To='+EncodingUtil.urlEncode('+917979024280', 'UTF-8')+'&From='+EncodingUtil.urlEncode('+13203907456', 'UTF-8')+'&Twiml='+EncodingUtil.urlEncode('<Response><Say>Your code is working Congratulations!</Say></Response>','UTF-8');
		req.setBody(payload);
        
        Http http = new Http();
		HTTPResponse res = http.send(req);
		System.debug(res.getBody());
        if(res.getStatusCode()==200){
            system.debug('Code Succesful');
        }
        else{
            system.debug('Not Successful');
        }
        return sid;
    }
    public Static string makecallout_for_sms(String Phone, String content){
        String sid='';
        return sid;
    }
    @AuraEnabled
    public static String GenerateWithEinteinGenAI(){
        return '';
    }
}